# fly.toml app configuration file generated for universum-backend on 2025-05-28T02:02:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'universum-backend'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
